= Abstract

When Anatolia shifted from 90% Christian to 90% Muslim between the 11th and 16th centuries, did modes of sacred performance cross the confessional boundary? This study examines whether the Abdalan-i Rum's practice of holy foolishness—transgressive behavior, feigned madness, deliberate marginalization—represents continuity with Byzantine _saloi_ traditions or independent Islamic development. If continuity can be demonstrated, it challenges rigid periodization separating "Byzantine" from "Islamic" Anatolia and suggests conversion preserved as much as it replaced.

Byzantine _vitae_ (Leontios of Neapolis's _Life of Simeon Salos_, 6th c.; the _Life of Andrew the Fool_, 10th c.) and Turkish _menakibname_ and _velayetname_ compiled generations posthumously suggest notable parallels. The Abdalan-i Rum constituted a distinctive antinomian dervish collectivity characterized by celibacy, extreme asceticism, and transgressive public performance, distinguishing their practices from contemporaneous Anatolian Sufi orders. Early abdal figures including Baba Ilyas (before 1240) and Sarı Saltuk (13th c.) mirror earlier _saloi_ through ritual poverty, prophetic authority, and transgressive behavior. Fifteenth-century continuity appears in Abdal Musa and Kaygusuz Abdal (d. 1444) in Konya. Syncretic elements emerge in abdal narratives: Christian liturgical elements, Hızır/St. George and İlyas/Elijah identifications preserved in Hıdırellez festival observances (May 5-6), and Byzantine shrine conversions. Geographic distributions align with earlier _saloi_ patterns, clustering in Constantinople/Istanbul and Konya, regions with documented crypto-Christian communities through the nineteenth century.

Significant methodological constraints apply. Hagiographical topoi circulate transregionally, making convergent evolution as plausible as direct transmission. The temporal gap between Byzantine and Ottoman sources, combined with posthumous compilation of _menakibname_, obscures transmission mechanisms. Karakaya-Stump's work on indigenous Shi'i roots and Said's critique of orientalist essentialism demand rigorous source criticism. This study proposes that geographic clustering, syncretic vocabulary, and crypto-Christian persistence offer verifiable markers of religious transmission.

*Keywords:* Abdal dervishes, Byzantine holy fools, saloi, Anatolian conversion, religious syncretism, Bektashi order, hagiography, Kaygusuz Abdal
