= Abstract

When Anatolia shifted from 90% Christian to 90% Muslim between the 11th and 16th centuries, did modes of sacred performance cross the confessional boundary? This study examines whether the Abdalan-i Rum's practice of holy foolishness—transgressive behavior, feigned madness, deliberate marginalization—represents continuity with Byzantine _saloi_ traditions or independent Islamic development. If continuity can be demonstrated, it challenges rigid periodization separating "Byzantine" from "Islamic" Anatolia and suggests conversion preserved as much as it replaced.

Comparative analysis of Byzantine _vitae_ (Leontios of Neapolis's _Life of Simeon Salos_, 6th c.; the _Life of Andrew the Fool_, 10th c.) alongside Turkish _menakibname_ and _velayetname_ compiled generations posthumously suggests notable parallels. Abdal Musa and his disciple Kaygusuz Abdal (d. 1444) in fifteenth-century Konya exemplify practices resembling earlier _saloi_: antinomian performance, ritual poverty, prophetic authority. Syncretic elements emerge in abdal narratives, including Gospel of John invocations, saint veneration, sacramental wine use, and associations with St. Cosmas shrines. Geographic distributions align with earlier _saloi_ patterns: both traditions cluster in Constantinople/Istanbul and Konya, regions with documented crypto-Christian communities through the nineteenth century.

Significant methodological constraints apply. Hagiographical topoi circulate transregionally, making convergent evolution as plausible as direct transmission. The temporal gap between Byzantine and Ottoman sources, combined with posthumous compilation of _menakibname_, obscures transmission mechanisms. Karakaya-Stump's work on indigenous Shi'i roots and Said's critique of orientalist essentialism demand rigorous source criticism. This study proposes that geographic clustering, syncretic vocabulary, and crypto-Christian persistence offer verifiable markers of religious transmission.

*Keywords:* Abdal dervishes, Byzantine holy fools, saloi, Anatolian conversion, religious syncretism, Bektashi order, hagiography, Kaygusuz Abdal
