= Introduction

== The Holy Fool in Two Worlds

In the early sixth century, the monk Simeon arrived in Emesa from the desert and immediately began a calculated campaign of public degradation. He entered the city gates on Sunday morning dragging a dead dog, invaded the women's section of the bathhouse, overturned the tables of pastry vendors in the marketplace, and pretended to proposition a prostitute while pelting congregants with nuts during the liturgy. Leontios of Neapolis, writing his _Life of Simeon the Fool_ sometime around 640, insists these scandals concealed profound sanctity—that Simeon deliberately courted contempt to achieve spiritual humility and protect his gifts from vainglory. The bathhouse incident particularly shocked contemporaries: Simeon stripped naked among women, provoking their screams and the bathkeeper's blows, transforming sacred space into theater of deliberate pollution. Yet Leontios presents this transgression not as apostasy but as radical imitation of Christ's kenotic self-emptying, a performance of foolishness that paradoxically manifested divine wisdom.

Seven centuries later and five hundred miles east, in the newly Islamized landscape of Seljuk Anatolia, another charismatic figure enacted similarly transgressive spirituality. Baba Ilyas, leader of the Babailer dervishes, cultivated followers through ecstatic performances, celibate asceticism, and practices that scandalized settled Islamic society. His followers, known as Abdalan-i Rum—the "Substitutes of Anatolia"—embraced poverty so extreme it appeared as madness, rejected normative social bonds including marriage, and claimed prophetic authority that challenged both sultanic and ulama power. When their revolt erupted in 1240, Byzantine chroniclers and Seljuk officials alike described them in terms resonant with holy foolishness: possessed by divine madness, performing wonders, transgressing boundaries between sacred and profane. The _Menakibname_ tradition that preserved their memory depicts similar urban performances, similar strategic use of scandal, similar claims that apparent madness concealed esoteric knowledge.

Were these parallel developments, separated by confession and centuries? Or does the second tradition somehow descend from the first, holy foolishness persisting across Anatolia's religious transformation in ways that theological analysis alone cannot detect?

== The Problem: Religious Continuity Across Anatolia's Transformation

Between 1025 and 1600, Anatolia underwent one of history's most complete religious transformations. At the Battle of Manzikert in 1071, Byzantine control of eastern Anatolia collapsed before Seljuk Turkish forces. What followed was not merely military conquest but demographic and cultural revolution. The peninsula that had been approximately 90 percent Christian in the early eleventh century was 90 percent Muslim by 1600—a transformation more thorough than the Iberian Reconquista's reversal, more rapid than the Christianization of northern Europe. The Seljuk sultanate of Rum (1077-1308) gave way to the Ottoman Empire (1299-1922), consolidating Anatolia as the heartland of Sunni Islamic civilization.

Conventional historiography has treated this transformation as fundamental rupture. The narrative of demographic replacement—Turkic nomads displacing or absorbing Christian populations—dominates both nationalist Turkish historiography and Greek narratives of catastrophic loss. Byzantine studies and Ottoman studies have developed as largely separate fields, divided by periodization that treats 1071 or 1453 as civilizational caesura. Where continuity is acknowledged, it typically concerns material culture (architecture repurposed, trade routes maintained) or high theological discourse (falsafa building on Greek philosophy). The religious lives of ordinary people, particularly modes of devotional practice and performance, have received less attention as sites of potential continuity.

Yet certain forms of religious behavior appear in both Byzantine and Ottoman Anatolia with striking similarities. Among the most distinctive is holy foolishness—the deliberate performance of madness, poverty, and transgression as spiritual discipline. In Byzantine Christianity, the _salos_ (plural _saloi_) feigned insanity to achieve humility, concealed sanctity beneath scandal, and claimed prophetic authority precisely through violation of social norms. These figures haunted Byzantine cities from the sixth through eleventh centuries, documented in hagiographical texts that celebrate their calculated pollution of sacred spaces, their disruption of liturgical propriety, their strategic deployment of apparent madness.

In Ottoman Anatolia, particularly the thirteenth through sixteenth centuries, a parallel tradition emerged among the Abdalan-i Rum. These celibate dervishes, associated with the Bektashi and broader Alevi-Bektashi tradition, practiced extreme asceticism that contemporaries interpreted as madness, performed wonders that violated normative Islamic piety, and claimed authority that challenged both Sunni orthodoxy and political power. Like the Byzantine _saloi_, they concentrated in urban settings, particularly Constantinople/Istanbul and Konya. Like the _saloi_, they used transgressive performance to manifest spiritual authority. Like the _saloi_, they occupied an ambiguous position—simultaneously revered and suspect, orthodox and heterodox, mad and prophetic.

The central question this study addresses is whether these similarities represent cultural continuity, convergent evolution, or entirely independent development. Did Ottoman holy fools inherit practices from Byzantine predecessors through mechanisms of cultural transmission? Or did similar ascetic strategies emerge independently within Islamic Sufism, responding to parallel social conditions with parallel solutions? Or should we understand these as instances of convergence—unrelated traditions producing similar forms because holy foolishness serves universal religious functions?

== Why This Question Matters

This investigation carries significance beyond antiquarian curiosity about obscure ascetic practices. It addresses three interconnected scholarly concerns: theoretical models of religious change, methodological approaches to cultural transmission, and historiographical assumptions about Anatolian history.

Theoretically, the question tests competing paradigms about how religious traditions transform. Models emphasizing theological discontinuity—the fundamental alterity of Christianity and Islam—predict independent development: Byzantine _saloi_ derive from Pauline theology of foolishness for Christ's sake and Eastern Christian kenotic spirituality, while Abdalan-i Rum emerge from Islamic Sufi traditions of _majdhub_ (the divinely attracted) and _qalandar_ (antinomian dervishes). These traditions share superficial similarities but develop from distinct theological roots and serve different religious functions within incompatible cosmological systems. Continuity would be literary at most—hagiographical topoi circulating through translation—not practical transmission of embodied performance.

Conversely, models emphasizing practice over theology predict possible continuity. If religious life consists not merely in doctrinal propositions but in embodied disciplines, spatial practices, and performance repertoires, then these elements might transmit even across confessional boundaries. Holy foolishness as a _practice_—a set of techniques for managing charismatic authority, disrupting institutional power, and performing sanctity—might prove more portable than theology suggests. Just as architectural forms, agricultural techniques, and craft knowledge transmitted across Anatolia's Islamization, so too might repertoires of religious performance.

This study's approach to continuity carries important methodological implications. Recent scholarship, particularly Ayfer Karakaya-Stump's definitive work in _The Kizilbash-Alevis in Ottoman Anatolia_ (2020), has decisively demonstrated that Alevi-Bektashi theology developed from indigenous Islamic—specifically Shi'i—sources rather than representing Christian syncretism or heterodox amalgamation. Karakaya-Stump's rigorous analysis of doctrinal content, tracing Alevi cosmology to early Islamic _ghulat_ movements in Iraq and Syria, demolishes earlier interpretations that attributed Alevi heterodoxy to Christian contamination or Central Asian shamanism. Her intervention is methodologically crucial: it demonstrates that doctrinal genealogy requires analysis within intellectual history, not recourse to vague syncretism.

This study does not challenge Karakaya-Stump's findings regarding theology. Rather, it examines a different dimension of religious life: embodied practice, spatial geography, and performance repertoires. Karakaya-Stump herself notes that her focus on doctrinal content leaves open questions about "local practices and their relationship to Byzantine Christian traditions." The present analysis accepts that Abdalan-i Rum theology derives from Islamic sources while asking whether their _performative practices_—the specific techniques of holy foolishness—might show Byzantine influence. This distinction between theological genealogy and practical transmission allows for parallel developments: Islamic doctrinal frameworks might coexist with locally transmitted performance traditions, just as Islamic architectural forms adapted Byzantine building techniques without theological syncretism.

Historiographically, this investigation challenges the rigid periodization that separates "Byzantine" and "Islamic" Anatolia as discrete civilizational units. The conventional narrative treats 1071 or 1453 as absolute breaks, with Byzantine studies ending where Ottoman studies begins. Yet religious practices, particularly those embedded in local geography and urban spaces, might prove more resilient than political boundaries suggest. If holy foolishness persisted across confessional change, it would indicate that Anatolia's Islamization involved not merely replacement but complex processes of adaptation, where Christian populations converting to Islam brought embodied religious practices into their new confession, transforming both in the process.

== This Study's Approach

This study examines whether the Abdalan-i Rum's distinctive practice of holy foolishness represents cultural continuity with Byzantine _saloi_ traditions, convergent evolution of similar ascetic strategies, or entirely independent Islamic development. Rather than propose definitive conclusions—the evidence does not permit such certainty—it presents three converging lines of evidence that suggest continuity merits serious consideration as a working hypothesis requiring further investigation.

The first line of evidence derives from hagiographical comparison. Byzantine _vitae_ of Simeon Salos and Andrew the Fool share striking narrative parallels with Turkish _menakibname_ of Baba Ilyas, Sarı Saltuk, and Kaygusuz Abdal. Beyond generic ascetic topoi common to all hagiography, these texts describe specific performative techniques: bathhouse invasions, marketplace disruptions, feigned sexual transgression, prophetic utterances delivered through apparent madness. The geographic and material specificity of these parallels—references to particular urban locations, descriptions of architectural spaces, details of daily practice—suggest more than literary borrowing of conventional tropes.

The second line of evidence concerns geographic clustering. Both Byzantine _saloi_ and Abdalan-i Rum concentrate in identical locations: Constantinople/Istanbul and Konya. These cities served as major urban centers for both Byzantine Christianity and Ottoman Islam, sites where institutional religion encountered charismatic disruption. Ottoman tax registers and endowment documents reveal that Abdal _tekkes_ (lodges) often occupied sites of former Byzantine monasteries and churches. Shrines venerated as Hızır sites correspond to documented St. George shrines, preserving not merely general sacred geography but specific devotional locations across confessional boundaries.

The third line of evidence emerges from living traditions that preserve dual Christian-Islamic identifications. The Hıdırellez festival, celebrated on May 5-6, commemorates the meeting of Hızır and İlyas—figures identified with St. George and Elijah respectively. The festival date corresponds to the Eastern Orthodox celebration of St. George (May 6 Gregorian, April 23 Julian), and festival practices combine elements from both traditions. This ethnographic present provides a control on historical speculation: living communities maintain syncretistic traditions that encode the very continuities this study hypothesizes for the past.

Methodologically, the study prioritizes verifiable markers over speculative claims. Rather than argue from theological similarities (which might reflect convergence) or generic hagiographical parallels (which might represent literary borrowing), it focuses on specific, testable evidence: documented shrine locations, architectural reuse, festival calendars, geographic clustering in identical urban neighborhoods. These material and spatial markers provide external constraints on interpretation, limiting the range of plausible explanations.

== Scope, Sources, and Limitations

The chronological scope extends from the sixth century—the earliest Byzantine holy fool _vitae_—through the sixteenth century, when the Bektashi order formalized and domesticated earlier Abdal antinomianism. The critical transition period spans the eleventh through thirteenth centuries, from the Seljuk conquest to the Babai Revolt and early Ottoman expansion. This longue durée perspective captures both Byzantine and Ottoman manifestations while acknowledging a significant temporal gap: tenth-century Byzantine sources precede thirteenth-century Abdal sources by two hundred years, during which direct evidence of transmission mechanisms remains elusive.

Geographically, the study focuses on western Anatolia—the former Byzantine heartland that became Ottoman territory earliest and most completely. Constantinople/Istanbul receives particular attention as the imperial capital of both empires, while Konya serves as a second major urban center where both traditions flourished. This geographic limitation acknowledges that religious dynamics in eastern Anatolia, the Arab borderlands, and the Balkans followed different patterns.

The source base combines Greek hagiography (Leontios's _Life of Simeon_, Rydén's critical edition of Andrew the Fool), Turkish _menakibname_ and _velayetname_ (compiled centuries after their subjects' deaths, requiring critical caution), Ottoman archival materials (tax registers documenting _tekke_ locations, persecution records), and ethnographic observations of contemporary Hıdırellez celebrations. Each source type presents methodological challenges: hagiography's rhetorical conventions, _menakibname_'s posthumous compilation, archival lacunae, and the risks of projecting contemporary practices onto the medieval past.

Several methodological constraints must be acknowledged upfront. The temporal gap between Byzantine and Ottoman sources obscures direct transmission mechanisms. Hagiographical topoi circulate transregionally through literary channels, meaning that narrative parallels might reflect borrowing of textual conventions rather than continuity of embodied practices. Karakaya-Stump's critique of orientalist assumptions about Alevi "syncretism" applies forcefully to any argument about Christian influences on Islamic traditions. The alternative hypothesis—convergent evolution, whereby similar social conditions generate similar ascetic strategies independently—remains equally plausible on available evidence.

This study therefore proposes testable hypotheses rather than definitive conclusions. It argues that geographic, hagiographical, and ethnographic evidence converges to make continuity a serious possibility worthy of further investigation, while acknowledging that current evidence cannot decisively rule out convergence or independent development.

== Roadmap

Following this introduction and the literature review presented in Chapter 2, the analysis proceeds through five substantive chapters and a conclusion.

Chapter 3 examines Byzantine _saloi_, establishing the baseline for comparison. It analyzes the theological roots of Christian holy foolishness in Pauline kenotic theology and apophatic mysticism, then examines the sixth-century _Life of Simeon Salos_ and tenth-century _Life of Andrew the Fool_ as exemplary texts. The chapter emphasizes the urban contexts of holy foolishness, the specific performance techniques deployed, and the social functions these figures served—simultaneously critiquing institutional power and claiming prophetic authority through strategic transgression.

Chapter 4 turns to the Abdalan-i Rum, tracing their emergence in thirteenth-century Anatolia through figures like Baba Ilyas and Sarı Saltuk, their consolidation in the fourteenth and fifteenth centuries through Abdal Musa and Kaygusuz Abdal, and their eventual absorption into formalized Bektashi structures in the sixteenth century. The chapter establishes the Abdals' distinctive characteristics—celibacy, extreme asceticism, associations with madness, antinomian practice—distinguishing them from other dervish groups like Qalandars and Haydaris while noting functional similarities to Byzantine _saloi_.

Chapter 5 presents the evidence for continuity across three domains. First, it compares hagiographical narratives in detail, identifying specific parallels beyond generic topoi. Second, it maps the geographic clustering of both traditions, documenting shrine locations and urban neighborhoods where _saloi_ and Abdal practices concentrated. Third, it analyzes syncretic elements in Abdal traditions—the Hıdırellez festival, Hızır/St. George and İlyas/Elijah identifications, Christian liturgical remnants in _menakibname_ narratives—as potential markers of transmission.

Chapter 6 conducts comparative analysis, systematically assessing similarities and differences. It examines convergent features (urban performance, transgressive behavior, prophetic authority through madness) alongside divergences (theological frameworks, institutional contexts, gender dynamics). The chapter evaluates alternative explanations—literary borrowing, convergent evolution, independent development—against the geographic and ethnographic evidence.

Chapter 7 addresses counter-arguments and implications. It engages Karakaya-Stump's indigenous Shi'i thesis directly, clarifying how this study's focus on practice complements rather than contradicts her theological analysis. It considers convergent evolution seriously, asking whether similar social conditions might generate similar ascetic responses. It examines possible transmission mechanisms—crypto-Christian communities, shared sacred geography, oral tradition—while acknowledging their speculative nature. Finally, it explores implications for understanding Anatolian Islamization as a complex process of negotiation rather than simple replacement.

The conclusion synthesizes findings, articulates this study's contribution to debates about religious continuity and change, and proposes directions for future research—particularly the need for systematic archaeological survey of shrine sites and oral history collection among communities maintaining Hıdırellez traditions.
