= Literature Review

== Introduction

The historiography of Anatolia's Islamization has long oscillated between two competing paradigms: syncretic continuity and violent rupture. Scholarship on the Byzantine _saloi_ (holy fools) and the Ottoman-era _Abdalan-i Rum_ (Fools of Rum) epitomizes this bifurcation. Vryonis's monumental _The Decline of Medieval Hellenism in Asia Minor and the Process of Islamization from the Eleventh through the Fifteenth Century_ positioned Turkification as fundamentally disruptive, a process that systematically dismantled Byzantine Christian culture through demographic replacement and institutional violence. Conversely, Hasluck's earlier _Christianity and Islam Under the Sultans_ emphasized cultural persistence, identifying widespread shrine sharing and syncretistic practices that suggested deeper continuities beneath nominal religious conversion. Recent scholarship, particularly the work of Karakaya-Stump on indigenous Anatolian Shi'ism and Karamustafa's analyses of antinomian dervish movements, has productively destabilized this binary, revealing more complex patterns of religious formation that resist reductivist categorization.

This literature review engages four interconnected historiographical problems: the relationship between literary topoi and lived religious practice; the tension between rupture and continuity frameworks; the specific traditions of Byzantine holy foolishness and Anatolian Abdal mysticism; and the methodological challenges inherent in cross-confessional comparative analysis. The synthesis demonstrates that while scholarship has established robust frameworks for understanding both Byzantine _saloi_ and _Abdalan-i Rum_ as discrete phenomena, the question of transmission mechanisms, convergent evolution, and shared cultural matrices remains productively unresolved. This study contributes to these debates by triangulating hagiographical, geographic, and ethnographic evidence to propose testable hypotheses about religious continuity in Anatolia's longue durée.

== Historiographical Paradigms

The study of holy foolishness across religious traditions confronts two fundamental methodological challenges that structure subsequent interpretation: the historicity of hagiographical sources and the conceptual frameworks applied to religious change. These challenges have generated competing scholarly paradigms that continue to shape the field.

Ivanov's comparative study of holy fools in Byzantium, Islam, and the medieval West questions the historicity of holy fool narratives, arguing that such figures function primarily as literary topoi that express theological ideals rather than document actual religious practitioners. His analysis emphasizes hagiography's rhetorical dimensions, suggesting that the recurring narrative patterns across diverse traditions indicate literary borrowing and theological construction rather than independent historical phenomena. This skepticism toward source reliability extends White's influential argument in _Metahistory_ that all historiography constitutes narrative construction shaped by underlying tropological structures. From this perspective, scholarly attempts to recover "authentic" historical practices risk misrecognizing literary conventions as empirical data.

Krueger's _Writing and Holiness_ offers a more nuanced counterposition, arguing that Byzantine hagiography, while certainly rhetorical, nonetheless reflects and actively shapes lived religious practices within specific urban contexts. Her analysis of sixth- and seventh-century Constantinopolitan holy fool narratives demonstrates how these texts engaged contemporary theological controversies, monastic politics, and urban social dynamics in ways that presuppose audience familiarity with actual holy fool performances. The specificity of urban topography, contemporary ecclesiastical debates, and detailed descriptions of public performances suggest that while hagiographers certainly employed literary conventions, they worked from lived traditions that their audiences recognized and inhabited. Rydén's critical edition of the _Life of Andrew the Fool_ similarly demonstrates how tenth-century Byzantine texts encode specific historical details about urban religious culture even as they deploy standardized hagiographical tropes.

This study adopts a position of critical realism: hagiographical texts are irreducibly rhetorical constructions that employ literary conventions and serve theological agendas, yet they simultaneously reflect, shape, and document lived religious behaviors within identifiable historical contexts. The methodological challenge becomes distinguishing between literary borrowing, convergent cultural evolution, and actual historical transmission—a problem particularly acute when examining phenomena separated by religious boundaries and temporal gaps. As Geertz's concept of "thick description" emphasizes, contextual specificity provides the crucial framework for interpretive adequacy.

The second foundational debate concerns conceptual frameworks for understanding Anatolia's Islamization. Vryonis's comprehensive synthesis positioned the process as fundamentally discontinuous, driven by Turkish migration, Byzantine institutional collapse, and systematic Islamization campaigns. His massive documentation of Byzantine churches converted to mosques, Christian communities subjected to devşirme recruitment, and Greek linguistic retreat before Turkish advancement painted Islamization as demographic replacement rather than cultural synthesis. While Vryonis acknowledged some continuities, his framework emphasized rupture, reflecting mid-twentieth-century nation-state historiographies that mapped contemporary Greek-Turkish antagonisms onto medieval Anatolia.

Hasluck's earlier anthropologically-informed work presented the diametric opposite: an Anatolia characterized by extensive shrine sharing, Muslim-Christian ritual overlap, and syncretistic saint veneration that suggested profound cultural continuities beneath nominal religious boundaries. His documentation of Muslim veneration at Christian shrines, Christian participation in Muslim festivals, and shared saints like Hızır-St. George indicated that ordinary religious practice often transcended official confessional categories. However, as Karakaya-Stump and others have noted, Hasluck's framework reflected colonial assumptions about "folk religion" as degraded forms of "pure" doctrinal traditions, essentializing both Islam and Christianity as monolithic systems subsequently corrupted through peasant ignorance.

Recent scholarship has productively moved beyond this binary. Karakaya-Stump's systematic deconstruction of the Köprülü paradigm demonstrates how earlier syntheses imposed diffusionist assumptions that obscured indigenous Anatolian religious formations. Her emphasis on Anatolian Shi'ism's roots in early Islamic _ghulat_ movements, rather than Central Asian shamanism or Christian heterodoxy, repositions Alevi-Bektashi traditions as authentically Islamic developments that require analysis within Islamic intellectual history rather than as syncretic hybrids. Peacock's work on Islamization similarly emphasizes vernacular Islamic traditions' internal diversity, questioning frameworks that position "orthodox" and "heterodox" as stable analytical categories. These interventions create space for analyzing religious continuities and transformations without presupposing either pure origins or syncretic contamination.

== Byzantine Holy Fools and the _Saloi_ Tradition

The Byzantine tradition of holy foolishness (_salosynē_) emerged from theological currents emphasizing radical kenosis, apophatic mysticism, and the rejection of worldly wisdom articulated in Pauline texts like 1 Corinthians 4:10: "We are fools for Christ's sake." The sixth-century _Life of Simeon Salos_, attributed to Leontios of Neapolis, established the hagiographical archetype: a ascetic who abandons the desert for urban anonymity, deliberately performs scandalous behaviors to conceal his sanctity, and exercises prophetic authority through seemingly mad utterances and actions. Simeon's calculated transgressions—entering women's bathhouses, associating with prostitutes, disrupting church services—constitute deliberate performances of social pollution that simultaneously critique worldly values and protect the saint from vainglory through public dishonor.

Krueger's analysis demonstrates that holy fool narratives encode sophisticated theological arguments about authentic sanctity in an increasingly institutionalized church. The sixth-century proliferation of holy fool vitae coincided with Justinianic ecclesiastical centralization and theological controversy over Origenism and Chalcedonian Christology. Holy fools' urban spectacles functioned as anti-institutional critiques, suggesting that authentic holiness might bypass ecclesiastical structures entirely, manifesting instead through apparently secular or even scandalous performances that only the spiritually discerning could recognize. Their feigned madness enacted apophatic theology somatically, embodying the fundamental incomprehensibility of divine wisdom to worldly understanding.

Saward's theological analysis positions holy foolishness within broader Christian traditions of sacred inversion and liminal sanctity. The holy fool inhabits the social position Douglas identifies in _Purity and Danger_ as maximally dangerous: deliberately transgressing purity boundaries to generate prophetic authority through strategic pollution. This liminality, which Turner theorizes as "betwixt and between" normative social structures, becomes permanent rather than transitional, creating what Turner terms "professional liminars" who embody communitas against hierarchical structure. The Byzantine _saloi_ thus represent not individual eccentricity but a recognized religious type with specific theological genealogy and social functions.

The _Life of Andrew the Fool_, in Rydén's critical edition, expands holy foolishness into elaborate apocalyptic vision and theological instruction, suggesting tenth-century developments toward more explicitly didactic functions. Andrew's extended eschatological visions, delivered through mad utterances, position holy fool discourse as vehicle for theological speculation that might prove controversial in more official contexts. The text's detailed topographical references to Constantinopolitan churches, forums, and neighborhoods indicate urban audiences familiar with specific locations where actual holy fool performances might occur.

Yet significant gaps remain in Byzantine holy fool scholarship. Comparative analysis with Islamic traditions remains limited, with Ivanov's work providing one of few systematic cross-confessional examinations. The relationship between literary representations and actual practices requires further specification: while Krueger convincingly demonstrates that texts reflect lived traditions, the precise sociology of Byzantine holy foolishness—its practitioners' social origins, the extent and duration of performances, the mechanisms of social recognition—remains obscure. Most crucially for this study, Byzantine scholarship has not systematically examined holy foolishness's potential transmission to or convergent development with Islamic mystical traditions in Anatolia's transitional zones.

== _Abdalan-i Rum_ and Anatolian Heterodox Mysticism

Scholarship on _Abdalan-i Rum_ and related Anatolian mystical traditions has undergone fundamental reorientation in recent decades, destabilizing earlier synthesist paradigms while opening new analytical possibilities. The dominant interpretive framework for much of the twentieth century derived from Köprülü's pioneering synthesis, which positioned Anatolian heterodoxy as syncretic amalgamation of Central Asian Turkish shamanism, heterodox Islamic mysticism, and residual Christianized elements absorbed through conversion. Köprülü's _Early Mystics in Turkish Literature_ established a genealogy tracing Alevi-Bektashi traditions through Central Asian Yasavi mysticism back to pre-Islamic Turkish religious culture, with Christian influences understood as superficial accretions onto fundamentally shamanistic substrates.

Karakaya-Stump's systematic critique has demonstrated this paradigm's methodological nationalism and diffusionist assumptions. Her analysis reveals how Köprülü's framework projected twentieth-century Turkish national identity formation onto medieval religious history, privileging Central Asian Turkish origins while marginalizing or dismissing indigenous Anatolian developments. More fundamentally, the Köprülü synthesis misrecognized Alevi-Bektashi theology's _ghulat_ Shi'i roots—its distinctive doctrines of divine manifestation through Ali, antinomian interpretations of Islamic law, and esoteric cosmologies—as syncretic corruption rather than authentic development within Islamic intellectual history. Karakaya-Stump's reconstruction positions Anatolian Alevism as continuous with early Islamic _ghuluw_ movements that migrated westward from Iraq and Syria, developing distinctive forms in Anatolia's specific social and political contexts but remaining fundamentally Islamic rather than crypto-shamanistic or crypto-Christian phenomena.

This crucial intervention requires careful calibration for the present study. Karakaya-Stump convincingly establishes that Alevi-Bektashi theology derives from Islamic sources and must be analyzed as Islamic tradition, not syncretic hybrid. However, her focus on doctrinal genealogy and theological content leaves open questions about practice, performance, and local sacred geographies where Christian-Islamic interactions might manifest differently than in formal theology. The _Abdalan-i Rum_—literally "Fools of Rum," with Rum denoting Byzantine Anatolia—represent a specific mystical collectivity whose very nomenclature suggests geographic and possibly cultural distinctiveness.

Karamustafa's magisterial _God's Unruly Friends_ provides the most comprehensive analysis of _Abdalan-i Rum_ as distinct from other antinomian dervish movements. His reconstruction, drawing on hostile Sunni sources, sympathetic hagiographies, and archival documentation of Ottoman persecution, identifies the Abdals as twelfth- to sixteenth-century itinerant mystics characterized by extreme asceticism, celibacy, social deviance, and deliberate transgression of Islamic behavioral norms. Unlike Qalandars and Haydaris who shared some antinomian practices, Abdals cultivated specific associations with madness, maintained celibacy more strictly, and demonstrated particular geographic concentration in western Anatolia—the former Byzantine heartland.

Karamustafa carefully distinguishes between historical Abdal practices and their later absorption into formalized Bektashi orders. The Bektashi synthesis, occurring primarily in the fifteenth and sixteenth centuries, domesticated earlier Abdal antinomianism within more institutionalized structures connected to Janissary corps patronage and Ottoman imperial politics. Mélikoff's work on Bektashi formation demonstrates how the order retrospectively claimed Hacı Bektaş Veli (thirteenth century) as founder despite the formal order postdating him by two centuries, and how the _Velayetname_'s compilation occurred centuries after Hacı Bektaş's lifetime, requiring methodological caution about reading later texts as straightforward historical sources for earlier periods.

The figure of Sarı Saltuk epitomizes these interpretive complexities. The _Saltukname_'s epic narratives of Saltuk's missionary activities in the Balkans, miraculous transformations, and culture-hero exploits blend historical memory, hagiographical convention, and folkloric elaboration in ways that resist simple source criticism. Karamustafa's analysis of the _Saltukname_ emphasizes vernacular piety and Islamization through charismatic religious authority rather than doctrinal instruction. Saltuk's legendary ability to assume different forms, perform miracles, and navigate between Christian and Islamic contexts reflects the ambiguous religious landscape of thirteenth- and fourteenth-century Anatolia and the Balkans, where formal confessional boundaries remained porous and individual religious authority might transcend institutional affiliation.

Ocak's work on the Babai Revolt (1239-1241) positions Baba Ilyas and related figures as proto-Abdal movements that challenged both Seljuk political authority and mainstream Islamic orthodoxy. The revolt's suppression and subsequent persecution of related mystical movements created conditions where antinomian practices might strategically deploy seeming madness and social transgression as protective camouflage, similar to Byzantine holy fools' protective foolishness. This functional parallel—transgressive performance as simultaneously prophetic authority and protective concealment—suggests possible convergent evolution even absent direct cultural transmission.
